#  Pyrogram - Telegram MTProto API Client Library for Python
#  Copyright (C) 2017-present Dan <https://github.com/delivrance>
#
#  This file is part of Pyrogram.
#
#  Pyrogram is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Pyrogram is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Pyrogram.  If not, see <http://www.gnu.org/licenses/>.

from typing import Dict, Optional

from pyrogram import enums, raw, types

from ..object import Object


class MessageContent(Object):
    """A message content.

    Parameters:
        type (:obj:`~pyrogram.enums.MessageMediaType`, *optional*):
            The attached media of the message.
            This field will contain the enumeration type of the media.
            You can use ``media = getattr(media, media.type.value)`` to access the media.

        audio (:obj:`~pyrogram.types.Audio`, *optional*):
            Message is an audio file, information about the file.

        document (:obj:`~pyrogram.types.Document`, *optional*):
            Message is a general file, information about the file.

        photo (:obj:`~pyrogram.types.Photo`, *optional*):
            Message is a photo, information about the photo.

        sticker (:obj:`~pyrogram.types.Sticker`, *optional*):
            Message is a sticker, information about the sticker.

        animation (:obj:`~pyrogram.types.Animation`, *optional*):
            Message is an animation, information about the animation.

        game (:obj:`~pyrogram.types.Game`, *optional*):
            Message is a game, information about the game.

        giveaway (:obj:`~pyrogram.types.Giveaway`, *optional*):
            Message is a giveaway, information about the giveaway.

        giveaway_winners (:obj:`~pyrogram.types.GiveawayWinners`, *optional*):
            A giveaway with public winners was completed.

        invoice (:obj:`~pyrogram.types.Invoice`, *optional*):
            Message is a invoice, information about the invoice.
            `More about payments » <https://core.telegram.org/bots/api#payments>`_

        story (:obj:`~pyrogram.types.Story`, *optional*):
            Message is a story, information about the story.

        video (:obj:`~pyrogram.types.Video`, *optional*):
            Message is a video, information about the video.

        voice (:obj:`~pyrogram.types.Voice`, *optional*):
            Message is a voice message, information about the file.

        video_note (:obj:`~pyrogram.types.VideoNote`, *optional*):
            Message is a video note, information about the video message.

        contact (:obj:`~pyrogram.types.Contact`, *optional*):
            Message is a shared contact, information about the contact.

        location (:obj:`~pyrogram.types.Location`, *optional*):
            Message is a shared location, information about the location.

        venue (:obj:`~pyrogram.types.Venue`, *optional*):
            Message is a venue, information about the venue.

        web_page (:obj:`~pyrogram.types.WebPage`, *optional*):
            Message was sent with a webpage preview.

        poll (:obj:`~pyrogram.types.Poll`, *optional*):
            Message is a native poll, information about the poll.

        dice (:obj:`~pyrogram.types.Dice`, *optional*):
            A dice containing a value that is randomly generated by Telegram.

        paid_media (:obj:`~pyrogram.types.PaidMediaInfo`, *optional*):
            The message is a paid media message.

        checklist (:obj:`~pyrogram.types.Checklist`, *optional*):
            The message is a checklist message.
    """

    def __init__(
        self,
        *,
        type: "enums.MessageMediaType",
        audio: Optional["types.Audio"] = None,
        document: Optional["types.Document"] = None,
        photo: Optional["types.Photo"] = None,
        sticker: Optional["types.Sticker"] = None,
        animation: Optional["types.Animation"] = None,
        game: Optional["types.Game"] = None,
        giveaway: Optional["types.Giveaway"] = None,
        giveaway_winners: Optional["types.GiveawayWinners"] = None,
        invoice: Optional["types.Invoice"] = None,
        story: Optional["types.Story"] = None,
        video: Optional["types.Video"] = None,
        voice: Optional["types.Voice"] = None,
        video_note: Optional["types.VideoNote"] = None,
        contact: Optional["types.Contact"] = None,
        location: Optional["types.Location"] = None,
        venue: Optional["types.Venue"] = None,
        web_page: Optional["types.WebPage"] = None,
        poll: Optional["types.Poll"] = None,
        dice: Optional["types.Dice"] = None,
        paid_media: Optional["types.PaidMediaInfo"] = None,
        checklist: Optional["types.Checklist"] = None,
    ):
        super().__init__()

        self.type = type
        self.audio = audio
        self.document = document
        self.photo = photo
        self.sticker = sticker
        self.animation = animation
        self.game = game
        self.giveaway = giveaway
        self.giveaway_winners = giveaway_winners
        self.invoice = invoice
        self.story = story
        self.video = video
        self.voice = voice
        self.video_note = video_note
        self.contact = contact
        self.location = location
        self.venue = venue
        self.web_page = web_page
        self.poll = poll
        self.dice = dice
        self.paid_media = paid_media
        self.checklist = checklist

    @staticmethod
    async def _parse(
        client,
        media: "raw.base.MessageMedia",
        message: Optional["raw.base.TextWithEntities"] = None,
        users: Dict[int, "raw.types.User"] = {},
        chats: Dict[int, "raw.types.Chat"] = {},
    ) -> "MessageContent":
        photo = None
        location = None
        contact = None
        venue = None
        game = None
        giveaway = None
        giveaway_winners = None
        invoice = None
        story = None
        audio = None
        voice = None
        animation = None
        video = None
        video_note = None
        sticker = None
        document = None
        web_page = None
        poll = None
        dice = None
        paid_media = None
        checklist = None

        media_type = enums.MessageMediaType.UNSUPPORTED

        if isinstance(media, raw.types.MessageMediaPhoto):
            photo = types.Photo._parse(client, media.photo, media.ttl_seconds)
            media_type = enums.MessageMediaType.PHOTO
        elif isinstance(media, raw.types.MessageMediaGeo):
            location = types.Location._parse(media.geo)
            media_type = enums.MessageMediaType.LOCATION
        elif isinstance(media, raw.types.MessageMediaGeoLive):
            location = types.Location._parse_media(media)
            media_type = enums.MessageMediaType.LOCATION
        elif isinstance(media, raw.types.MessageMediaContact):
            contact = types.Contact._parse(client, media)
            media_type = enums.MessageMediaType.CONTACT
        elif isinstance(media, raw.types.MessageMediaVenue):
            venue = types.Venue._parse(client, media)
            media_type = enums.MessageMediaType.VENUE
        elif isinstance(media, raw.types.MessageMediaGame):
            game = types.Game._parse(client, media)
            media_type = enums.MessageMediaType.GAME
        elif isinstance(media, raw.types.MessageMediaGiveaway):
            giveaway = types.Giveaway._parse(client, media, chats)
            media_type = enums.MessageMediaType.GIVEAWAY
        elif isinstance(media, raw.types.MessageMediaGiveawayResults):
            giveaway_winners = await types.GiveawayWinners._parse(client, media, users, chats)
            media_type = enums.MessageMediaType.GIVEAWAY_WINNERS
        elif isinstance(media, raw.types.MessageMediaInvoice):
            invoice = types.Invoice._parse(client, media)
            media_type = enums.MessageMediaType.INVOICE
        elif isinstance(media, raw.types.MessageMediaStory):
            story = await types.Story._parse(client, media, media.peer, users, chats)
            media_type = enums.MessageMediaType.STORY
        elif isinstance(media, raw.types.MessageMediaDocument):
            doc = media.document

            if isinstance(doc, raw.types.Document):
                attributes = {type(i): i for i in doc.attributes}

                file_name = getattr(
                    attributes.get(
                        raw.types.DocumentAttributeFilename, None
                    ), "file_name", None
                )

                if raw.types.DocumentAttributeAnimated in attributes:
                    video_attributes = attributes.get(raw.types.DocumentAttributeVideo, None)

                    if video_attributes and video_attributes.round_message:
                        video_note = types.VideoNote._parse(client, doc, video_attributes, media.ttl_seconds)
                        media_type = enums.MessageMediaType.VIDEO_NOTE
                    else:
                        animation = types.Animation._parse(client, doc, video_attributes, file_name)
                        media_type = enums.MessageMediaType.ANIMATION
                elif raw.types.DocumentAttributeSticker in attributes:
                    sticker = await types.Sticker._parse(client, doc, attributes)
                    media_type = enums.MessageMediaType.STICKER
                elif raw.types.DocumentAttributeVideo in attributes:
                    video_attributes = attributes[raw.types.DocumentAttributeVideo]

                    if video_attributes.round_message:
                        video_note = types.VideoNote._parse(client, doc, video_attributes, media.ttl_seconds)
                        media_type = enums.MessageMediaType.VIDEO_NOTE
                    else:
                        video = types.Video._parse(client, doc, video_attributes, file_name, media.ttl_seconds, media.video_cover, media.video_timestamp, media.alt_documents)
                        media_type = enums.MessageMediaType.VIDEO
                elif raw.types.DocumentAttributeAudio in attributes:
                    audio_attributes = attributes[raw.types.DocumentAttributeAudio]

                    if audio_attributes.voice:
                        voice = types.Voice._parse(client, doc, audio_attributes, media.ttl_seconds)
                        media_type = enums.MessageMediaType.VOICE
                    else:
                        audio = types.Audio._parse(client, doc, audio_attributes, file_name)
                        media_type = enums.MessageMediaType.AUDIO
                else:
                    document = types.Document._parse(client, doc, file_name)
                    media_type = enums.MessageMediaType.DOCUMENT
        elif isinstance(media, raw.types.MessageMediaWebPage):
            media_type = enums.MessageMediaType.WEB_PAGE
            web_page = types.WebPage._parse(client, media)
        elif isinstance(media, raw.types.MessageMediaPoll):
            poll = await types.Poll._parse(
                client,
                media,
                description=types.FormattedText._parse(
                    client,
                    message
                ) if message else None,
                users=users,
                chats=chats
            )
            media_type = enums.MessageMediaType.POLL
        elif isinstance(media, raw.types.MessageMediaDice):
            dice = types.Dice._parse(client, media)
            media_type = enums.MessageMediaType.DICE
        elif isinstance(media, raw.types.MessageMediaPaidMedia):
            paid_media = types.PaidMediaInfo._parse(client, media)
            media_type = enums.MessageMediaType.PAID_MEDIA
        elif isinstance(media, raw.types.MessageMediaToDo):
            media_type = enums.MessageMediaType.CHECKLIST
            checklist = types.Checklist._parse(client, media, users, chats)

        return MessageContent(
            type=media_type,
            audio=audio,
            document=document,
            photo=photo,
            sticker=sticker,
            animation=animation,
            game=game,
            giveaway=giveaway,
            giveaway_winners=giveaway_winners,
            invoice=invoice,
            story=story,
            video=video,
            voice=voice,
            video_note=video_note,
            contact=contact,
            location=location,
            venue=venue,
            web_page=web_page,
            poll=poll,
            dice=dice,
            paid_media=paid_media,
            checklist=checklist
        )
